import type { BrokerConnection, CopierRule, PropAccount, RecentExecution, User } from "./types";

export const demoUser: User = {
  id: "user-demo",
  workspaceId: "workspace-demo",
  name: "Demo Operator",
  email: "operator@tradecopilot.local",
  role: "owner",
  webhookSecret: "demo-webhook-secret",
};

export const propAccounts: PropAccount[] = [
  {
    id: "leader-nq-01",
    ownerId: demoUser.id,
    name: "NQ Leader",
    firm: "Personal Futures",
    platform: "Tradovate",
    status: "online",
    balance: 52400,
    dailyPnl: 860,
    drawdownUsed: 18,
    maxDailyLoss: 2500,
    trailingDrawdownLimit: 3000,
    multiplier: 1,
    copyEnabled: true,
    latencyMs: 24,
  },
  {
    id: "apex-150k-a",
    ownerId: demoUser.id,
    name: "Apex 150K A",
    firm: "Apex Trader Funding",
    platform: "Rithmic",
    status: "online",
    balance: 151280,
    dailyPnl: 420,
    drawdownUsed: 32,
    maxDailyLoss: 5000,
    trailingDrawdownLimit: 4500,
    multiplier: 1,
    copyEnabled: true,
    latencyMs: 38,
  },
  {
    id: "topstep-150k-x",
    ownerId: demoUser.id,
    name: "Topstep X 150K",
    firm: "Topstep",
    platform: "ProjectX",
    status: "online",
    balance: 150740,
    dailyPnl: 210,
    drawdownUsed: 41,
    maxDailyLoss: 4500,
    trailingDrawdownLimit: 3000,
    multiplier: 1,
    copyEnabled: true,
    latencyMs: 44,
  },
  {
    id: "tradeify-100k",
    ownerId: demoUser.id,
    name: "Tradeify 100K",
    firm: "Tradeify",
    platform: "Tradovate",
    status: "paused",
    balance: 100120,
    dailyPnl: -780,
    drawdownUsed: 57,
    maxDailyLoss: 3000,
    trailingDrawdownLimit: 2500,
    multiplier: 0.5,
    copyEnabled: false,
    latencyMs: 30,
  },
  {
    id: "bulenox-50k",
    ownerId: demoUser.id,
    name: "Bulenox 50K",
    firm: "Bulenox",
    platform: "Rithmic",
    status: "locked",
    balance: 49880,
    dailyPnl: -1480,
    drawdownUsed: 84,
    maxDailyLoss: 1500,
    trailingDrawdownLimit: 2000,
    multiplier: 0.25,
    copyEnabled: false,
    latencyMs: 42,
  },
];

export const copierRules: CopierRule[] = [
  {
    id: "rule-futures-core",
    ownerId: demoUser.id,
    name: "Core Futures Copier",
    leaderAccountId: "leader-nq-01",
    followerAccountIds: [
      "apex-150k-a",
      "topstep-150k-x",
      "tradeify-100k",
      "bulenox-50k",
    ],
    symbolMap: {
      NQ: "NQ",
      MNQ: "MNQ",
      ES: "ES",
      MES: "MES",
    },
    maxContractsPerFollower: 4,
    copyStopsAndTargets: true,
    autoFlattenOnRuleBreach: true,
    enabled: true,
  },
];

export const brokerConnections: BrokerConnection[] = [
  {
    id: "broker-sim-tradovate",
    ownerId: demoUser.id,
    name: "Tradovate simulator",
    platform: "Tradovate",
    mode: "simulation",
    status: "connected",
    accountIds: ["leader-nq-01", "tradeify-100k"],
    credentialVaultId: null,
    liveEnabled: false,
    lastError: null,
    lastValidatedAt: null,
    createdAt: "2026-05-01T13:45:00.000Z",
    lastHeartbeatAt: "2026-05-01T13:45:00.000Z",
  },
  {
    id: "broker-sim-rithmic",
    ownerId: demoUser.id,
    name: "Rithmic simulator",
    platform: "Rithmic",
    mode: "simulation",
    status: "connected",
    accountIds: ["apex-150k-a", "bulenox-50k"],
    credentialVaultId: null,
    liveEnabled: false,
    lastError: null,
    lastValidatedAt: null,
    createdAt: "2026-05-01T13:45:00.000Z",
    lastHeartbeatAt: "2026-05-01T13:45:00.000Z",
  },
  {
    id: "broker-sim-projectx",
    ownerId: demoUser.id,
    name: "ProjectX simulator",
    platform: "ProjectX",
    mode: "simulation",
    status: "connected",
    accountIds: ["topstep-150k-x"],
    credentialVaultId: null,
    liveEnabled: false,
    lastError: null,
    lastValidatedAt: null,
    createdAt: "2026-05-01T13:45:00.000Z",
    lastHeartbeatAt: "2026-05-01T13:45:00.000Z",
  },
];

export const recentExecutions: RecentExecution[] = [
  {
    id: "ex-1842",
    ownerId: demoUser.id,
    time: "09:42:18",
    strategy: "London breakout",
    symbol: "NQ",
    side: "buy",
    quantity: 2,
    copied: 3,
    blocked: 1,
    status: "partial",
  },
  {
    id: "ex-1837",
    ownerId: demoUser.id,
    time: "09:16:03",
    strategy: "VWAP reclaim",
    symbol: "ES",
    side: "sell",
    quantity: 1,
    copied: 4,
    blocked: 0,
    status: "complete",
  },
  {
    id: "ex-1831",
    ownerId: demoUser.id,
    time: "08:57:45",
    strategy: "Opening range",
    symbol: "NQ",
    side: "buy",
    quantity: 3,
    copied: 2,
    blocked: 2,
    status: "risk blocked",
  },
];
